"""Promotion ladder tests, plus the calibration gate that now stands in front of it.

The test this file replaces was:

    def test_calibration_has_fifty_labels_and_passes():
        report = from_csv("routebench/evalops/human_labels/labels.csv")
        assert report["n"] == 50 and report["kappa"] >= 0.6

It passed, and it asserted nothing. `labels.csv` was generated by writing one variable into both
the `human_score` and `judge_score` columns, so kappa was 1.0 by construction. A test that
cannot fail is worse than no test, because it occupies the place where the real check belongs.
The fixture now lives in `evalops/fixtures/` and the assertion has been inverted: a
fixture-provenance label must be REJECTED.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest
from aisys.audit import AuditLog
from evalops.calibrate import identity_hash, validate_bundle
from evalops.promote import promote
from evalops.rubrics import bundle_hash

FIXTURE_LABELS = Path(__file__).parent.parent / "evalops" / "fixtures" / "synthetic_selfagreement_labels.csv"


def _bundle(**overrides: object) -> dict[str, object]:
    """A minimal well-formed passing artifact, so each test can break exactly one field."""
    # Derived, not literal: the gate recomputes `bundle_id` from these fields.
    identity = {
        "variant_id": "v-test", "threshold": 0.5, "judge_config": {"model": "gpt-4.1-mini"},
        "rubric_bundle_hash": bundle_hash(), "dataset_hash": "abc123", "split_seed": 20260927,
        "annotations_hash": "ann-abc", "split_membership_hash": "mem-abc",
    }
    base: dict[str, object] = {
        "bundle_id": identity_hash(**identity),  # type: ignore[arg-type]
        "created_at": "2026-09-27T00:00:00+00:00",
        "variant_id": identity["variant_id"],
        "judge_config": identity["judge_config"],
        "threshold": identity["threshold"],
        "min_kappa": 0.74,
        "rubric_bundle_hash": identity["rubric_bundle_hash"],
        "dataset_hash": identity["dataset_hash"],
        "split_seed": identity["split_seed"],
        "annotations_hash": identity["annotations_hash"],
        "split_membership_hash": identity["split_membership_hash"],
        "dev_kappa": 0.80,
        "dev_n": 400,
        "selection_rule": "argmax dev kappa",
        "threshold_grid": [],
        "label_provenance_counts": {"human_expert_annotation": 400},
        "test_result": {
            "completion": {"paired": 200, "unjudged": 0, "completion_rate": 1.0, "judge_errors": {}},
            "tracks": {
                "human_judgment_of_response": {
                    "track": "human_judgment_of_response", "insufficient": False,
                    "n": 200, "kappa": 0.79, "defined": True, "observed_agreement": 0.9,
                    "passes_min_kappa": True, "interval": {"low": 0.70, "high": 0.86, "usable": True},
                    "reason": "",
                    # Per-track coverage is required by the hardened gate: overall completion can
                    # look fine while the primary track is thinly covered.
                    "n_labelled": 200, "track_completion": 1.0,
                },
            },
        },
    }
    base.update(overrides)
    return base


def _write(tmp_path: Path, payload: dict[str, object]) -> Path:
    p = tmp_path / "calibration_bundle.json"
    p.write_text(json.dumps(payload), encoding="utf-8")
    return p


# ---------------------------------------------------------------- the fixture must be refused


def test_synthetic_fixture_labels_are_self_agreeing_and_therefore_worthless():
    """Pins the original defect: the 'human' and 'judge' columns are identical by construction."""
    rows = [
        line.split(",")
        for line in FIXTURE_LABELS.read_text(encoding="utf-8").strip().splitlines()[1:]
    ]
    assert rows, "fixture should still exist as the negative example"
    assert all(human == judge for _id, human, judge in rows), (
        "the fixture is only meaningful as a demonstration that human_score == judge_score"
    )


# ---------------------------------------------------------------- the gate


def test_valid_artifact_passes_the_gate(tmp_path):
    ok, reasons = validate_bundle(_write(tmp_path, _bundle()))
    assert ok and reasons == []


def test_missing_artifact_blocks(tmp_path):
    ok, reasons = validate_bundle(tmp_path / "nope.json")
    assert not ok and "no calibration artifact" in reasons[0]


def test_unmeasured_bundle_blocks(tmp_path):
    ok, reasons = validate_bundle(_write(tmp_path, _bundle(test_result=None)))
    assert not ok and any("never measured on held-out data" in r for r in reasons)


def test_rubric_drift_blocks(tmp_path):
    ok, reasons = validate_bundle(_write(tmp_path, _bundle(rubric_bundle_hash="stale000")))
    assert not ok and any("rubric hash mismatch" in r for r in reasons)


def test_kappa_below_policy_blocks(tmp_path):
    payload = _bundle()
    payload["test_result"]["tracks"]["human_judgment_of_response"]["kappa"] = 0.7399  # type: ignore[index]
    ok, reasons = validate_bundle(_write(tmp_path, payload))
    assert not ok and any("below the 0.74 policy" in r for r in reasons)


def test_kappa_exactly_at_policy_passes(tmp_path):
    payload = _bundle()
    payload["test_result"]["tracks"]["human_judgment_of_response"]["kappa"] = 0.74  # type: ignore[index]
    ok, reasons = validate_bundle(_write(tmp_path, payload))
    assert ok, reasons


def test_undefined_kappa_blocks(tmp_path):
    """The NaN-through-the-gate defect: an undefined kappa must never be treated as passing."""
    payload = _bundle()
    track = payload["test_result"]["tracks"]["human_judgment_of_response"]  # type: ignore[index]
    track.update({"kappa": None, "defined": False, "reason": "single-class table"})
    ok, reasons = validate_bundle(_write(tmp_path, payload))
    assert not ok and any("undefined" in r for r in reasons)


def test_incomplete_coverage_blocks(tmp_path):
    payload = _bundle()
    payload["test_result"]["completion"] = {  # type: ignore[index]
        "paired": 150, "unjudged": 50, "completion_rate": 0.75, "judge_errors": {"provider_error": 50},
    }
    ok, reasons = validate_bundle(_write(tmp_path, payload))
    assert not ok and any("automated decision" in r for r in reasons)


def test_corrupt_artifact_blocks_rather_than_crashing(tmp_path):
    p = tmp_path / "calibration_bundle.json"
    p.write_text("{not json", encoding="utf-8")
    ok, reasons = validate_bundle(p)
    assert not ok and "unreadable" in reasons[0]


# ---------------------------------------------------------------- the ladder


def test_uncalibrated_judge_blocks_promotion_despite_high_quality(tmp_path):
    """A great-looking quality score must not ship behind an unvalidated judge."""
    audit = AuditLog(f"sqlite:///{tmp_path}/audit.db")
    result = promote(
        "shiny", 0.99, 0.80, lambda weight: 0.99, audit,
        calibration=_write(tmp_path, _bundle(test_result=None)),
    )
    assert result.blocked_by_calibration and result.stage == "blocked"
    assert not result.history, "the ladder must not run at all when the judge is untrusted"
    event = audit.rows()[-1][2]
    assert event["type"] == "model_promotion" and event["calibration_valid"] is False
    assert event["reasons"], "a blocked promotion must record why"


def test_valid_calibration_allows_full_rollout(tmp_path):
    audit = AuditLog(f"sqlite:///{tmp_path}/audit.db")
    result = promote(
        "good", 0.90, 0.88, lambda weight: 0.90, audit,
        calibration=_write(tmp_path, _bundle()),
    )
    assert result.stage == "full" and not result.rolled_back
    assert [h["stage"] for h in result.history] == ["shadow", "canary-5", "canary-25", "full"]


def test_regression_rolls_back_and_is_audited(tmp_path):
    audit = AuditLog(f"sqlite:///{tmp_path}/audit.db")
    result = promote(
        "worse", 0.9, 0.9, lambda weight: 0.7 if weight >= 0.05 else 0.9, audit,
        calibration=_write(tmp_path, _bundle()),
    )
    assert result.rolled_back and result.stage == "rollback"
    assert audit.rows()[-1][2]["type"] == "model_promotion"


def test_offline_gate_rolls_back_before_any_traffic(tmp_path):
    audit = AuditLog(f"sqlite:///{tmp_path}/audit.db")
    calls: list[float] = []
    result = promote(
        "bad", 0.50, 0.90, lambda weight: calls.append(weight) or 0.9, audit,  # type: ignore[func-returns-value]
        calibration=_write(tmp_path, _bundle()),
    )
    assert result.rolled_back and result.stage == "rollback"
    assert calls == [], "a failed offline gate must not send even shadow traffic"


def test_gate_can_be_skipped_but_the_skip_is_audited(tmp_path):
    audit = AuditLog(f"sqlite:///{tmp_path}/audit.db")
    result = promote("local", 0.9, 0.9, lambda weight: 0.9, audit, calibration=None)
    assert result.stage == "full"
    assert audit.rows()[-1][2]["calibration_checked"] is False


@pytest.mark.parametrize("min_kappa", [0.60, 0.74])
def test_artifact_accepted_at_a_weaker_policy_is_rejected_under_a_stricter_one(tmp_path, min_kappa):
    ok, _ = validate_bundle(_write(tmp_path, _bundle(min_kappa=0.60)), min_kappa=min_kappa)
    assert ok is (min_kappa <= 0.60)
